package io.spacerobot;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'akseli' at '10/7/16 8:41 PM' with Gradle 3.0
 *
 * @author akseli, @date 10/7/16 8:41 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
