import org.junit.Test;

import io.spacerobot.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'akseli' at '10/7/16 8:41 PM' with Gradle 3.0
 *
 * @author akseli, @date 10/7/16 8:41 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
